Script started on 2015年03月17日 (週二) 09時31分07秒
]0;H34036186@2015cpp: ~H34036186@2015cpp:~$ whoami;pwd pwd[C[C[C
H34036186
/home/H34036186
]0;H34036186@2015cpp: ~H34036186@2015cpp:~$ git config -l
user.name=bernice17824
user.email=H34036186@mail.ncku.edu.tw
email.name=H34036186@mail.ncku.edu.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.lab1.url=https://github.com/bernice17824/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
branch.master.remote=lab1
branch.master.merge=refs/heads/master
]0;H34036186@2015cpp: ~H34036186@2015cpp:~$ git clone https://github.com/bernice17824/lab1
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;H34036186@2015cpp: ~H34036186@2015cpp:~$ exit

Script done on 2015年03月17日 (週二) 09時32分29秒
